config/routes.rb
Rails.application.routes.draw do
  mount RailsPerformance::Engine , at: '/rails/performance' , as: 'rails_performance'

  resources :lessons
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "welcome#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/lesson.rb
class Lesson < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: %i[ show edit update destroy ]

  # GET /lessons
  def index
    @lessons = Lesson.all
  end

  # GET /lessons/1
  def show
  end

  # GET /lessons/new
  def new
    @lesson = Lesson.new
  end

  # GET /lessons/1/edit
  def edit
  end

  # POST /lessons
  def create
    @lesson = Lesson.new(lesson_params)

    if @lesson.save
      redirect_to @lesson, notice: "Lesson was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /lessons/1
  def update
    if @lesson.update(lesson_params)
      redirect_to @lesson, notice: "Lesson was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /lessons/1
  def destroy
    @lesson.destroy!
    redirect_to lessons_url, notice: "Lesson was successfully destroyed.", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lesson
      @lesson = Lesson.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def lesson_params
      params.require(:lesson).permit(:title, :video_url, :notes)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def benchmark(caption = '', &block)
    Benchmark.benchmark(caption) { |x| x.report { yield } }
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Demo Ruby Rails" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5">
      <%= yield %>
    </main>
  </body>
</html>

app/views/lessons/_form.html.erb
<%= form_with(model: lesson, class: "contents") do |form| %>
  <% if lesson.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(lesson.errors.count, "error") %> prohibited this lesson from being saved:</h2>

      <ul>
        <% lesson.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-200 dark:bg-gray-700 dark:border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :video_url %>
    <%= form.text_field :video_url, class: "block shadow rounded-md border border-gray-200 dark:bg-gray-700 dark:border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :notes %>
    <%= form.text_area :notes, rows: 4, class: "block shadow rounded-md border border-gray-200 dark:bg-gray-700 dark:border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/lessons/_lesson.html.erb
<div id="<%= dom_id lesson %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Title:</strong>
    <%= lesson.title %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Video url:</strong>
    <%= lesson.video_url %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Notes:</strong>
    <%= lesson.notes %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this lesson", lesson, class: "rounded-lg py-3 px-5 bg-gray-100 dark:bg-gray-800 inline-block font-medium" %>
    <%= link_to "Edit this lesson", edit_lesson_path(lesson), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 dark:bg-gray-800 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/lessons/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing lesson</h1>

  <%= render "form", lesson: @lesson %>

  <%= link_to "Show this lesson", @lesson, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 dark:bg-gray-800 inline-block font-medium" %>
  <%= link_to "Back to lessons", lessons_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 dark:bg-gray-800 inline-block font-medium" %>
</div>

app/views/lessons/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 dark:bg-green-900 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Lessons</h1>
    <%= link_to "New lesson", new_lesson_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="lessons" class="min-w-full">
    <%= render @lessons %>
  </div>
</div>

app/views/lessons/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New lesson</h1>

  <%= render "form", lesson: @lesson %>

  <%= link_to "Back to lessons", lessons_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 dark:bg-gray-800 inline-block font-medium" %>
</div>

app/views/lessons/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 dark:bg-green-900 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @lesson %>

    <%= link_to "Edit this lesson", edit_lesson_path(@lesson), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 dark:bg-gray-800 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this lesson", lesson_path(@lesson), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 dark:bg-gray-800 font-medium" %>
    </div>
    <%= link_to "Back to lessons", lessons_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 dark:bg-gray-800 inline-block font-medium" %>
  </div>
</div>

app/views/welcome/_section_erb.html.erb
<div class="flex flex-col md:flex-row items-center">
  <!-- Profile Section -->
  <div class="md:w-1/3 flex flex-col items-center md:items-start text-center md:text-left">
    <img class="w-24 h-24 rounded-full mb-4" src="/static/avatar.jpg" alt="Vitalii Avatar">
    <h1 class="text-xl font-bold"><%= full_name %></h1>
    <p class="text-gray-400"><%= description %></p>
  </div>

  <!-- Main Content Section -->
  <div class="md:w-2/3 mt-6 md:mt-0">
    <div class="aspect-w-16 aspect-h-9 border border-pink-300 rounded-lg overflow-hidden shadow-sm">
      <!-- Replace with image or video in the future -->
      <img class="object-cover" src="/static/screen.jpg" alt="New video cover">
    </div>
    <h2 class="text-lg font-semibold mt-3 flex items-center">
      New video!
      <svg class="w-6 h-6 ml-2" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"></path>
      </svg>
    </h2>
  </div>
</div>

app/views/welcome/_section_slim.html.slim
.flex.flex-col.md:flex-row.items-center
  / Profile Section
  .md:w-1/3.flex.flex-col.items-center.md:items-start.text-center.md:text-left
    img.w-24.h-24.rounded-full.mb-4[src="/static/avatar.jpg" alt="Vitalii Avatar"]
    h1.text-xl.font-bold = full_name
    p.text-gray-400 = description

  / Main Content Section
  .md:w-2/3.mt-6.md:mt-0
    .aspect-w-16.aspect-h-9.border.border-pink-300.rounded-lg.overflow-hidden.shadow-sm
      / Replace with image or video in the future
      img.object-cover[src="/static/screen.jpg" alt="New video cover"]
    h2.text-lg.font-semibold.mt-3.flex.items-center
      |  New video!
      svg.w-6.h-6.ml-2[fill="none" stroke="currentColor" viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"]
        path[stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"]

app/views/welcome/index.html.erb
<%= render "section_erb", full_name: "Vitalii Emeliantsev", description: "Short text about me or my tagline" %>